Реализован роутинг через history API, обработан клик по логотипу(кроме страницы авторизации). Добавлены две страницы
frontend-park-mail-ru/2024_1_Kayros pull request #4
Opened 2024-02-29 03:52 UTC by Skotyty

Страницы пока не оформлены. login, register

2024-02-29 08:34 UTC, novakf requested changes
Небольшие предложения по коду от меня, а так отлично)

2024-02-29 08:34 UTC, novakf commented on src/index.js
> +	.addRoute('/register', RegisterPage)
может лучше сразу вынести маршруты в отдельный объект и добавлять в роутер через цикл, их ведь потом много будет)

2024-02-29 08:34 UTC, novakf commented on src/router.js
> +class Router {
описание для jsDoc не забудь)

2024-02-29 08:34 UTC, novakf commented on src/router.js
> +		} else {
можно добавить в конце блока для первого условия return, и убрать else, чтобы вложенность уменьшить)

2024-02-29 08:34 UTC, novakf commented on src/router.js
> +		const route = this.routes.find((r) => r.path === path);
не сокращаем переменные) r -> route

2024-02-29 08:34 UTC, novakf commented on src/router.js
> +class Router {
и давай роутер в modules/ положим, а маршруты в src/routes/index.js

2024-03-01 10:12 UTC, AnnSkay commented on src/router.js
> +class Router {
@novakf а у нас нет запуска генерации доки при коммите? мы ж добавляли

2024-03-01 11:23 UTC, AnnSkay commented on src/components/Header/Header.js
> +			if (!window.location.pathname.includes('/login')) {
я тут подумала - глянь любые приложухи, где есть своя авторизация ) там вроде клк на лого тоже вызывает редирект на главную страницу, просто из-за отстуствия авторизации пользователя его редиректит обратно на авторизацию) и в этом случае мы уберем проверку, а оставим для всех лого

2024-03-01 11:23 UTC, AnnSkay commented on src/components/Header/Header.js
> +				router.navigate('/restaurants');
давай в папку, где будет лежать роут, вынесем в константу все урлы страниц и будем использовать через переменную) так потом легче будет изменить урл, если понадобится и отслеживать изменения)

2024-03-01 11:23 UTC, AnnSkay commented on src/index.js
> +// //const content = document.getElementById('content');
не оставляем закоменченный код)

2024-03-01 11:23 UTC, AnnSkay commented on src/pages/Login/Login.js
названия SignIn и SignUp лучше для понимания, чем Login и Register)

2024-03-01 11:23 UTC, AnnSkay commented on src/router.js
> +		} else {
я бы даже добавила так:
```
if (!currentRoute && !defaultRoute) {
    console.error('Any route did not found');
}

const route =  currentRoute ?? defaultRoute;
const page = new route.component(content);
page.render();
```

хотя я думаю для несуществующей страницы лучше добавить страницу-заглушку с кнопкой с возможностью с нее вернуться на главную)

2024-03-01 21:34 UTC, novakf commented on src/router.js
> +class Router {
Дока генерируется при коммите в generated/jsDocs на основе описания, которое заранее прописываем функциям и классам, само описание не генерится. Думаю, можно добавить правило для линтера на проверку наличия описания в js файликах

2024-03-03 08:03 UTC, AnnSkay commented on src/router.js
> +class Router {
это было бы хорошо, а то вдруг пропустим на ревью такое) запишу в задачи в бэклог, добавим как будет время

2024-03-03 21:52 UTC, Skotyty commented on src/index.js
> +	.addRoute('/register', RegisterPage)
Сделал

2024-03-03 21:52 UTC, Skotyty commented on src/router.js
> +class Router {
Сделал

2024-03-03 21:52 UTC, Skotyty commented on src/router.js
> +		} else {
Сделал

2024-03-03 21:52 UTC, Skotyty commented on src/router.js
> +		const route = this.routes.find((r) => r.path === path);
Сделал

2024-03-03 21:52 UTC, Skotyty commented on src/components/Header/Header.js
> +			if (!window.location.pathname.includes('/login')) {
Удалил проверку

2024-03-03 21:52 UTC, Skotyty commented on src/components/Header/Header.js
> +				router.navigate('/restaurants');
вынес

2024-03-03 21:53 UTC, Skotyty commented on src/index.js
> +// //const content = document.getElementById('content');
удалил комментарий

2024-03-03 22:45 UTC, novakf commented on src/pages/NotFound/NotFound.hbs
> +<div class="notFound">
предлагаю для названий классов и id использовать везде kebab_case, здесь, например, not-found

2024-03-03 22:59 UTC, novakf commented on src/pages/NotFound/NotFound.js
> +		 * @type {string}
переменные внутри функции наверное лишне описывать, только функции и классы может

2024-03-04 10:00 UTC, Skotyty commented on src/pages/NotFound/NotFound.hbs
> +<div class="notFound">
В js вроде нельзя в названиях класса использовать kebab-case, т.к. дефис интерпретируется, как минус. В id-шниках изменю

2024-03-04 10:05 UTC, AnnSkay commented on src/pages/NotFound/NotFound.hbs
> +<div class="notFound">
почему нельзя?) а как же методология бэм, мы пишем не на scc-in-js, поэтому "_" или "-" можно ипользовать)

2024-03-04 11:20 UTC, Skotyty commented on src/pages/NotFound/NotFound.js
> +		 * @type {string}
убрал описание

2024-03-04 11:21 UTC, Skotyty commented on src/pages/NotFound/NotFound.hbs
> +<div class="notFound">
изменил

2024-03-04 11:34 UTC, novakf commented on src/pages/NotFound/NotFound.js
> +		const returnButton = new Button(buttonBlock, { id: 'returnButton', content: 'Вернуться на главную' });
Здесь тоже у Button id returnButton в return-button или return-to-home, например)

2024-03-04 11:37 UTC, Skotyty commented on src/pages/NotFound/NotFound.js
> +		const returnButton = new Button(buttonBlock, { id: 'returnButton', content: 'Вернуться на главную' });
Исправил

2024-03-04 11:41 UTC, novakf approved these changes

2024-03-04 11:43 UTC, AnnSkay approved these changes

2024-03-04 11:43 UTC, merged